### ISSUE TITLE
Hide or Remove Dependency for Json processing on Gson from the global module

### ISSUE THREAD

**Issue by cklellie** [casualcore/casual-java#135]
Like with netty it would be nicer to have our dependency to gson for json processing not be part of the global module which is used to install casual-jca.
This is because it makes all other application deployed to the same app server use that same version of gson.

Investigate if it is possible to move this internally, though this is unlikely, as it needs to be available on the global module due to the usage within casual-api for reading the Configuration file and Fielded file.

Check if SPI would remove this dependency, delaying the loading of the gson module and issolating it. Unsure if this will work.
Change to use something other than gson which is build into java, jsonb? Though does that also has an implementation dependency?

Could potentially move the configuration and fielded code out of the casual-api and into another module(s) allowing for gson to be bundled rather than in the global module.

**Comment by aliothe** [comment]
Fixed in 3.2.49
