### ISSUE TITLE
casual-caller - incorrects logs when pool stickies are enabled and no sticky is present

### ISSUE THREAD

**Issue by TobiasLeo** [casualcore/casual-java#51]
Incorrect logs like `Failed to call service=<someservice> on stickied pool=null, falling through to normal flow.` happen. No service call has failed and pool=null is a give-away that something incorrect is happening

It happens here https://github.com/casualcore/casual-java/blob/dev/casual/casual-caller/src/main/java/se/laz/casual/connection/caller/FailoverAlgorithm.java#L190 if no sticky is set, but in this case an earlier check if the current transaction is actually stickied should be done to return without any form or logs that could indicate problems

**Comment by aliothe** [comment]
Moved to https://github.com/casualcore/casual-caller/issues/3
