### ISSUE TITLE
Using configuration file and a mode that does not exist in inbound startup will end up with nullptr

### ISSUE THREAD

**Issue by aliothe** [casualcore/casual-java#74]
It should not result in a nullptr.
It should log that that mode is not a supported mode and then set the mode to whatever we deem should be the default mode.

**Comment by aliothe** [comment]
{
    "outbound":
    {
	"unmanaged": true
    },
    "inbound": {
	"startup": {
	    "mode": "discovery",
	    "services": [
		"javaEcho"
	    ]
	}
    }
}
Example, using discovery instead of discover will result in a nullptr and no logging what actually went wrong.

**Comment by cklellie** [comment]
In version 3.2.47, this will now fail fast, with an appropriate error message.
