### ISSUE TITLE
Additional inbound startup modes for disabling and reverse inbound only.

### ISSUE THREAD

**Issue by cklellie** [casualcore/casual-java#86]
There can be scenarios where reverse inbound is used and normal inbound requests should not be allowed.
In a reverse inbound scenario, the inbound server port is not uses, so there is no need to have the inbound server running unless you want to allow normal direct inbound requests.
There is also a scenario where you may not wish to allow any inbound connections at all to the server. Therefore inbound should be disabled.

Two new modes for inbound start will be added in addition to IMMEDIATE, DISCOVER and TRIGGER.
DISABLE - no inbound or reverse inbound is possible.
REVERSE_ONLY - no inbound server is started, only reverse inbound is possible.

Question - should REVERSE_ONLY fail if there is no reverse configuration provided on startup?

**Comment by aliothe** [comment]
If you set REVERSE_ONLY without any reverse configuration, it would be helpful if it would fail pointing out that that part of the configuration is indeed missing.

**Comment by aliothe** [comment]
Casual JCA follows the JCA standard 1.7 with some additional things, such as reverse inbound.
In the 1.7 standard, outbound and inbound is defined for a bidirectional resource adapter - ergo it is not optional in any way.
